<script setup lang="ts">
import { fetchGraphFailures, fetchGraphFailureStats, type GraphFailureRecord } from '@/api/admin/knowledge'
import { onMounted, ref, computed } from 'vue'
const rows = ref<GraphFailureRecord[]>([])
const stats = ref<Record<string, unknown>>({})
const loading = ref(false)
const page = ref(1); const pageSize = 12; const reason = ref(''); const stage = ref(''); const batchId = ref('')
async function load() { loading.value = true; try { const [records, summary] = await Promise.all([fetchGraphFailures({ limit: 5000, batchId: batchId.value || undefined, reasonCode: reason.value || undefined, stage: stage.value || undefined }), fetchGraphFailureStats(batchId.value || undefined)]); rows.value = records; stats.value = summary; page.value=1 } finally { loading.value = false } }
onMounted(load)
const visible = computed(()=>rows.value.slice((page.value-1)*pageSize,page.value*pageSize))
const reasonText=(code:string)=>({VOCABULARY:'关系或端点类型不在封闭词表',UNANCHORED:'端点/组合成员没有被正文引文锚定',UNGROUNDED:'引文没有逐字命中正文',MALFORMED:'候选结构或实体形状不合法',SELF_LOOP:'两端归一后是同一实体'} as Record<string,string>)[code]??'候选未通过校验'
</script>
<template>
  <div class="admin-page">
    <header class="page-head"><div><p class="eyebrow">Graph Diagnostics</p><h1>图谱构建诊断</h1><p>这里记录的是模型候选被事实校验拒绝或构建阶段跳过的账本，不代表已有图谱事实全部失效。</p></div><button class="toolbar-btn" type="button" :disabled="loading" @click="load">刷新</button></header>
    <section class="explain-grid"><article><b>词表</b><span>关系类型或端点类型不匹配，候选不会入图。</span></article><article><b>锚定</b><span>正文或 quote 没有逐字支持候选，系统保守丢弃。</span></article><article><b>重试</b><span>只有抽取、写入等外部失败允许重试，事实校验拒绝不可重试。</span></article><article><b>当前批次汇总</b><span>记录 {{ stats.failed ?? rows.length }} 条 · 可重试 {{ stats.retryable ?? 0 }} 条 · 批次 {{ stats.batches ?? '—' }}</span></article></section>
    <section class="panel"><div class="filters"><el-select v-model="stage" clearable placeholder="全部阶段"><el-option label="事实校验" value="VALIDATION"/><el-option label="抽取" value="EXTRACT"/><el-option label="写入" value="WRITE"/></el-select><el-select v-model="reason" clearable placeholder="全部原因"><el-option label="词表" value="VOCABULARY"/><el-option label="端点无出处" value="UNANCHORED"/><el-option label="引文未命中" value="UNGROUNDED"/><el-option label="畸形" value="MALFORMED"/></el-select><el-input v-model="batchId" clearable placeholder="构建批次"/><button class="query-btn" type="button" @click="load">筛选</button></div><el-table v-loading="loading" :data="visible" stripe empty-text="暂无诊断记录"><el-table-column prop="occurredAt" label="时间" width="170"/><el-table-column prop="batchId" label="批次" width="145" show-overflow-tooltip/><el-table-column prop="docNo" label="文档" width="100"/><el-table-column prop="stage" label="阶段" width="100"/><el-table-column label="判定" width="190"><template #default="scope"><strong>{{ scope.row.reasonCode }}</strong><small>{{ reasonText(scope.row.reasonCode) }}</small></template></el-table-column><el-table-column prop="entityKey" label="候选实体" width="160"/><el-table-column prop="detail" label="具体原因" min-width="360" show-overflow-tooltip/><el-table-column label="重试" width="75"><template #default="scope">{{ scope.row.retryable ? '可重试' : '无需重试' }}</template></el-table-column><el-table-column type="expand"><template #default="scope"><div class="detail-box"><b>候选/校验说明</b><p>{{ scope.row.detail }}</p><dl><dt>原始候选</dt><dd>{{ scope.row.rawCandidate || '未记录' }}</dd><dt>规范化端点</dt><dd>{{ scope.row.normalizedHeadKind }} {{ scope.row.normalizedHead }} -> {{ scope.row.normalizedTailKind }} {{ scope.row.normalizedTail }}</dd><dt>关系/引文</dt><dd>{{ scope.row.relation || '未记录' }} · {{ scope.row.quote || '未记录' }}</dd><dt>切片</dt><dd>{{ scope.row.chunkId || '未记录' }}</dd></dl><span>批次 {{ scope.row.batchId }} · {{ scope.row.occurredAt }}</span></div></template></el-table-column></el-table><el-pagination v-if="rows.length>pageSize" v-model:current-page="page" class="pager" layout="total, prev, pager, next" :page-size="pageSize" :total="rows.length" /></section>
  </div>
</template>
<style scoped>
.admin-page{display:grid;gap:var(--ys-space-5)}.page-head{display:flex;justify-content:space-between;gap:var(--ys-space-4);align-items:end}.eyebrow{margin:0;color:var(--color-primary-strong);font-size:var(--ys-font-xs);font-weight:700;letter-spacing:.1em;text-transform:uppercase}.page-head h1{margin:.25rem 0;font-size:var(--ys-font-2xl)}.page-head p{margin:0;color:var(--color-text-secondary)}.panel,.explain-grid article{background:var(--color-bg-surface);border:var(--card-border);border-radius:var(--card-radius);padding:var(--ys-space-4);box-shadow:var(--card-shadow)}.toolbar-btn,.query-btn{min-height:38px;padding:0 var(--ys-space-4);border:1px solid var(--color-border);border-radius:var(--ys-radius-sm);background:var(--color-bg-surface);cursor:pointer}.query-btn{background:var(--color-primary);color:var(--color-text-inverse);border:0}.toolbar-btn:hover{border-color:var(--color-primary);color:var(--color-primary-strong)}.explain-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:var(--ys-space-3)}.explain-grid article{display:grid;gap:var(--ys-space-1)}.explain-grid span,small{color:var(--color-text-muted);font-size:var(--ys-font-xs)}.filters{display:flex;gap:var(--ys-space-2);margin-bottom:var(--ys-space-4)}.detail-box{display:grid;gap:var(--ys-space-1);padding:var(--ys-space-3);background:var(--color-bg-subtle);border-inline-start:3px solid var(--color-primary)}.detail-box p{margin:0;color:var(--color-text-secondary)}.detail-box dl{display:grid;grid-template-columns:90px minmax(0,1fr);gap:var(--ys-space-1) var(--ys-space-3);margin:var(--ys-space-2) 0}.detail-box dt{color:var(--color-text-muted)}.detail-box dd{margin:0;color:var(--color-text-secondary);font-size:var(--ys-font-xs);overflow-wrap:anywhere}.pager{justify-content:flex-end;margin-top:var(--ys-space-4)}@media(max-width:760px){.explain-grid{grid-template-columns:1fr}.filters{flex-wrap:wrap}}
</style>
