/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiChatMessageList: typeof import('./src/components/ai/ChatMessageList.vue')['default']
    AiChatSessionList: typeof import('./src/components/ai/ChatSessionList.vue')['default']
    AiCitationList: typeof import('./src/components/ai/CitationList.vue')['default']
    AiConflictList: typeof import('./src/components/ai/ConflictList.vue')['default']
    AiMessageContent: typeof import('./src/components/ai/MessageContent.vue')['default']
    AiPendingApprovalCard: typeof import('./src/components/ai/PendingApprovalCard.vue')['default']
    AiQuickPromptBar: typeof import('./src/components/ai/QuickPromptBar.vue')['default']
    AiRecommendationCards: typeof import('./src/components/ai/RecommendationCards.vue')['default']
    AuthAuthShell: typeof import('./src/components/auth/AuthShell.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    KnowledgeGraphCanvas: typeof import('./src/components/knowledge/GraphCanvas.vue')['default']
    OrderAfterSaleDialog: typeof import('./src/components/order/AfterSaleDialog.vue')['default']
    OrderReviewDialog: typeof import('./src/components/order/ReviewDialog.vue')['default']
    ReviewReviewSection: typeof import('./src/components/review/ReviewSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopFavoriteButton: typeof import('./src/components/shop/FavoriteButton.vue')['default']
    ShopProductCard: typeof import('./src/components/shop/ProductCard.vue')['default']
    ShopSearchBox: typeof import('./src/components/shop/SearchBox.vue')['default']
    UiErrorState: typeof import('./src/components/ui/ErrorState.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
